# Generated by Django 6.0.3 on 2026-03-09 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('viewed', 'Viewed'), ('duplicated', 'Duplicated'), ('imported', 'Imported'), ('exported', 'Exported'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('other', 'Other')], help_text='Type of action performed', max_length=20)),
                ('model_name', models.CharField(db_index=True, help_text='Full model name (app.Model)', max_length=255)),
                ('object_id', models.CharField(db_index=True, help_text='Primary key of the affected object', max_length=255)),
                ('object_str', models.CharField(blank=True, help_text='String representation of the object', max_length=500)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Additional data about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='easix_activ_timesta_f2264e_idx'), models.Index(fields=['model_name', 'object_id'], name='easix_activ_model_n_064b5a_idx'), models.Index(fields=['user', '-timestamp'], name='easix_activ_user_id_81d198_idx'), models.Index(fields=['action'], name='easix_activ_action_022235_idx')],
            },
        ),
    ]
